server:
  port: 8086

spring:
  jpa:
    show-sql: true
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      show-components: ALWAYS

logging:
  level:
    org.springframework: DEBUG