version: '3.8'

name: terrier

services:
  postgres:
    image: postgres:17-alpine
    container_name: terrier-postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: terrier
      POSTGRES_PASSWORD: terrier
      POSTGRES_DB: terrier
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts/:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: terrier-redis
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: